apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: smtp
spec:
  type: bindings.smtp
  version: v1
  metadata:
    - name: host
      value: "smtp.gmail.com"
    - name: port
      value: "465"
    - name: user
      value: ""
    - name: password
      value: ""
    - name: emailFrom
      value: "no-reply@hotelbooking.com"
    - name: subject
      value: "Booking confirmation"
